CREATE DATABASE clinic;
CREATE TABLE patients(id INT GENERATED ALWAYS AS IDENTITY,
name VARCHAR,
date_of_birth DATE,
PRIMARY KEY(id)
);


CREATE TABLE medical_histories(id INT GENERATED ALWAYS AS IDENTITY,
admited_at TIMESTAMP,
patient_id INT REFERENCES patients(id),
status VARCHAR,
PRIMARY KEY(id)
);

CREATE TABLE treatments(id INT GENERATED ALWAYS AS IDENTITY,
type VARCHAR,
name VARCHAR,
PRIMARY KEY(id)
);