CREATE DATABASE vet_clinic;
CREATE TABLE animals(id INT GENERATED ALWAYS AS IDENTITY,name VARCHAR,date_of_birth DATE,escape_attempts INT,neutered BOOLEAN,weight_kg DECIMAL(4,2),PRIMARY KEY(id));
ALTER TABLE animals ADD species VARCHAR;

CREATE TABLE owners(id INT GENERATED ALWAYS AS IDENTITY,full_name VARCHAR,age INT,PRIMARY KEY(id));
CREATE TABLE species(id INT GENERATED ALWAYS AS IDENTITY,name VARCHAR,PRIMARY KEY(id));
ALTER TABLE animals  DROP COLUMN species;
ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);
